import { PhysicsStage } from './types';

export const PHYSICS_STAGES: PhysicsStage[] = [
  {
    id: 1,
    name: "Question 1: Suspension Bridge Deck",
    mechanicalObject: "Suspension Bridge Deck (e.g., Tacoma Narrows)",
    subtitle: "Aeroelastic Flutter & Torsional Mechanical Resonance",
    vibrationMode: "2nd Torsional Eigenmode & Standing Wave",
    description: "A flexible suspended roadway deck subjected to periodic vortex shedding matching its torsional natural frequency.",
    realWorldPhenomenon: "1940 Tacoma Narrows Bridge Collapse (Wind-induced aerodynamic torsional flutter)",
    formula: "f_n = (1 / 2L) * √(G * J / I_p)  or  f_s = (St * v) / D",
    differentialEquation: "I_p · (d²θ/dt²) + c_t · (dθ/dt) + k_t · θ = M_wind · cos(ω t)",
    resonanceBehavior: "Vortex shedding at 4.8 Hz pumps rotational momentum into the deck with zero phase lag. Because damping is negligible (ζ = 0.008), torsional displacement angle θ doubles every cycle until steel suspenders fatigue and snap.",
    mechanicalParams: {
      stiffness: "k_torsion = 1.4 × 10⁸ N·m/rad",
      mass: "I_polar = 3.2 × 10⁶ kg·m²",
      dampingRatio: "ζ = 0.008 (critically underdamped)",
      naturalFreqFormula: "f_n = (1 / 2π)·√(k_t / I_p)",
      realFailure: "Tacoma Narrows Bridge deck twisted past 45° and sheared suspender cables in 42 mph winds."
    },
    clueHint: "Torsional natural frequency formula: f_n = (1 / 2π)·√(k_t / I_p). With k_t = 1.4×10⁸ N·m/rad and I_p = 3.2×10⁶ kg·m², calculate the eigenfrequency before pulsing.",
    targetFrequency: 4.8,
    tolerance: 0.35,
    perfectBand: 0.1,
    minFrequency: 1.0,
    maxFrequency: 10.0,
    step: 0.1,
    unit: "Hz",
    breakdownThreshold: 3500,
    difficulty: "Easy",
    structureType: "bridge",
    teachingPrompts: [
      "Why did moderate 42 mph winds destroy the Tacoma Narrows Bridge while higher gusts earlier caused no harm?",
      "Observe the stationary node line along the center lane: why did the two sidewalks oscillate out-of-phase?",
      "How do tuned mass dampers and aerodynamic truss vents prevent torsional resonance in modern bridges?"
    ],
    physicsExplanation: "When the vortex shedding frequency matches the bridge deck's torsional natural frequency (4.8 Hz), the system absorbs aerodynamic energy without dissipation. Lack of structural damping causes torsional amplitude to grow exponentially until steel suspenders snap."
  },
  {
    id: 2,
    name: "Question 2: Skyscraper Tower & TMD",
    mechanicalObject: "Skyscraper Tower with Tuned Mass Damper (e.g., Taipei 101)",
    subtitle: "First-Order Lateral Cantilever Sway & Wind Vortex Shedding",
    vibrationMode: "Fundamental 1st Cantilever Bending Mode",
    description: "An 800-meter skyscraper behaving as a vertical cantilever beam excited by periodic von Kármán wind vortex shedding.",
    realWorldPhenomenon: "Taipei 101 (660-tonne pendulum damper) & Citigroup Center cross-wind crisis",
    formula: "f_1 ≈ 46 / H  or  ω_n = 3.52 * √(E*I / (m * L⁴))",
    differentialEquation: "m · (d²x/dt²) + c · (dx/dt) + k · x = F_vortex · cos(ω t)",
    resonanceBehavior: "Periodic vortex shedding peels off alternating tower facades at 1.25 Hz. At resonance, the mechanical phase lag is 90°, transferring maximum aerodynamic work into lateral cantilever deflection, pushing structural columns past elastic strain limits.",
    mechanicalParams: {
      stiffness: "k_lateral = 2.8 × 10⁷ N/m",
      mass: "m_effective = 45,000 tonnes",
      dampingRatio: "ζ = 0.012 (increased to 0.045 by TMD)",
      naturalFreqFormula: "f_n = (1 / 2π)·√(k / m)",
      realFailure: "Without a tuned mass damper, typhoon vortex shedding would induce over 1.5m lateral sway, cracking exterior glass welds."
    },
    clueHint: "Fundamental lateral sway: f_n = (1 / 2π)·√(k / m). Effective mass is 4.5×10⁷ kg. Tall towers sway with very low frequency (1 to 2 Hz).",
    targetFrequency: 1.25,
    tolerance: 0.12,
    perfectBand: 0.04,
    minFrequency: 0.2,
    maxFrequency: 4.0,
    step: 0.05,
    unit: "Hz",
    breakdownThreshold: 4500,
    difficulty: "Easy",
    structureType: "skyscraper",
    teachingPrompts: [
      "Why do tall skyscrapers vibrate with very low fundamental frequencies (1 to 2 seconds per sway cycle)?",
      "Why does the golden Tuned Mass Damper sphere swing 180° out-of-phase relative to the building frame?",
      "Where is mechanical bending stress concentrated in a vertical cantilever during 1st mode oscillation?"
    ],
    physicsExplanation: "Tall buildings act as vertical cantilever beams with high mass and compliance. Transverse wind eddies peel off alternate sides at a frequency f_s = St · v / D. At 1.25 Hz, resonant lateral deflection overwhelms the building's internal viscoelastic damping."
  },
  {
    id: 3,
    name: "Question 3: Crystal Wine Glass Chalice",
    mechanicalObject: "Crystal Wine Glass Chalice (Acoustic-Mechanical Excitation)",
    subtitle: "Circumferential Flexural Eigenmode & Acoustic Forcing",
    vibrationMode: "Rim Elliptical Quadrupole Mode (n = 2)",
    description: "A thin-walled lead crystal glass driven into forced mechanical vibration by high-amplitude acoustic sound pressure waves.",
    realWorldPhenomenon: "Shattering crystal glassware using sustained resonant vocal or loudspeaker frequencies",
    formula: "f_rim = (1 / 2π) * (t / R²) * √(E / (12 * ρ * (1 - ν²)))",
    differentialEquation: "m · (d²u/dt²) + c · (du/dt) + k_rim · u = P_acoustic · cos(ω t)",
    resonanceBehavior: "Lead crystal has an extreme Quality factor (Q > 800, ζ < 0.0006). When driven at 440 Hz, acoustic pressure waves deform the rim into alternating ellipses; with negligible damping, hoop strain builds cycle-by-cycle until brittle Griffith micro-fractures tear the glass apart.",
    mechanicalParams: {
      stiffness: "E = 62 GPa (Young's Modulus of Crystal)",
      mass: "m_chalice = 180 grams",
      dampingRatio: "Q > 800 (Quality Factor; extreme low internal damping)",
      naturalFreqFormula: "f_acoustic = (v_sound / 2π)·√(E/ρ)",
      realFailure: "The rim deforms between alternating ellipses until tensile hoop stress surpasses the brittle glass Griffith fracture limit."
    },
    clueHint: "Concert pitch acoustic resonance: This thin lead crystal chalice has its fundamental rim quadrupole mode tuned to international concert pitch A4 (440 Hz).",
    targetFrequency: 440.0,
    tolerance: 4.0,
    perfectBand: 1.0,
    minFrequency: 200.0,
    maxFrequency: 800.0,
    step: 1.0,
    unit: "Hz",
    breakdownThreshold: 6000,
    difficulty: "Easy",
    structureType: "cantilever",
    teachingPrompts: [
      "Why must the acoustic sound wave match the glass natural pitch to within ±1% to shatter it?",
      "Why does crystal glass with high Quality Factor (Q) shatter much easier than ordinary soda-lime glass?",
      "How does rubbing a wet finger around a glass rim excite stick-slip mechanical vibration?"
    ],
    physicsExplanation: "Crystal has an extraordinarily high mechanical Quality Factor (Q > 800), meaning almost zero energy is lost as heat. Sustained 440 Hz sound waves flex the rim back and forth. Amplitude builds continuously until tensile hoop stresses trigger instant catastrophic brittle fracture."
  },
  {
    id: 4,
    name: "Question 4: Helicopter Airframe & Rotor",
    mechanicalObject: "Helicopter Airframe & Articulated Rotor System",
    subtitle: "Ground Resonance & Mechanical Damper Instability",
    vibrationMode: "Coupled Rotor Lead-Lag & Airframe Landing Gear Rocking Mode",
    description: "An articulated helicopter rotor experiencing self-exciting mechanical ground resonance when touching down.",
    realWorldPhenomenon: "Helicopter Ground Resonance Destruction (Rapid airframe disintegration on runway)",
    formula: "ω_resonant = |Ω_rotor ± ω_lead-lag|  matching  ω_landing_gear",
    differentialEquation: "M_fuselage · (d²x/dt²) + C_strut · (dx/dt) + K_strut · x = m_blade · e · Ω² · cos(Ω t)",
    resonanceBehavior: "An uneven landing shifts a lead-lag blade damper, displacing the rotor's rotational center of gravity. As the rotor whirls at 16.5 Hz, the unbalanced centrifugal vector locks in resonance with the landing gear's rocking frequency, tearing the transmission off within 3 seconds.",
    mechanicalParams: {
      stiffness: "k_oleo_strut = 5.2 × 10⁵ N/m",
      mass: "m_airframe = 3,400 kg",
      dampingRatio: "ζ = 0.02 (faulty lead-lag blade damper)",
      naturalFreqFormula: "ω_n = √(k_landing_gear / m_fuselage)",
      realFailure: "Unbalanced rotor blade center of gravity sets off violent airframe rocking that rips the transmission and tail boom off in seconds."
    },
    clueHint: "Coupled ground resonance: Fuselage natural rocking on oleo struts ω_n = √(k_strut / m_airframe). Calculate natural frequency: √(5.2×10⁵ / 3400) / (2π) ≈ 16.5 Hz.",
    targetFrequency: 16.5,
    tolerance: 0.5,
    perfectBand: 0.15,
    minFrequency: 5.0,
    maxFrequency: 35.0,
    step: 0.1,
    unit: "Hz",
    breakdownThreshold: 7500,
    difficulty: "Easy",
    structureType: "helicopter",
    teachingPrompts: [
      "How can a ground vehicle or helicopter destroy itself purely from mechanical coupling without flying?",
      "What role do the hydraulic lead-lag dampers on each rotor blade play in preventing ground resonance?",
      "Why does ground resonance cease if the pilot pulls pitch and lifts completely off the ground?"
    ],
    physicsExplanation: "Ground resonance occurs when an articulated rotor blade shifts out of position, throwing the rotor's center of gravity off-center. When the resulting rotational oscillation matches the fuselage rocking natural frequency on its landing gear springs (16.5 Hz), destructive feedback tears the airframe apart."
  },
  {
    id: 5,
    name: "Question 5: Offshore Deepwater Drillstring",
    mechanicalObject: "Offshore Deepwater Drillstring & Riser Pipe",
    subtitle: "Torsional Stick-Slip & Vortex-Induced Vibration (VIV)",
    vibrationMode: "Torsional Shear Elastic Wind-Up & Lateral VIV Lock-In",
    description: "A 4-kilometer steel drill pipe spinning deep underground, subject to violent torsional stick-slip oscillation and ocean current vortices.",
    realWorldPhenomenon: "Oil & Gas well drillstring twist-offs and deep sea riser fatigue failures",
    formula: "f_torsion = (n / 4L) * √(G / ρ)  or  T = J * G * (θ / L)",
    differentialEquation: "J · (d²θ/dt²) + c_mud · (dθ/dt) + (G·J / L) · θ = T_motor - T_friction(dθ/dt)",
    resonanceBehavior: "Underground rock friction locks the drill bit, turning the 4 km pipe into a giant torsional spring. When released at its 24.6 Hz torsional eigenfrequency, angular velocity snaps to 3x normal speed, creating cyclic shear shockwaves that shear threaded pin joints.",
    mechanicalParams: {
      stiffness: "G_steel = 79.3 GPa (Shear Modulus)",
      mass: "Length = 4,200 m (Weight = 120 tonnes)",
      dampingRatio: "ζ = 0.018 (mud fluid damping)",
      naturalFreqFormula: "f_n = (1 / 4L)·√(G / ρ)",
      realFailure: "Stick-slip winding causes the drill bit to stall, storing torsional energy, then unleash at 3x rotary speed until drill collars shear."
    },
    clueHint: "Torsional wave propagation in 4.2 km drillstring: f_n = (1 / 4L)·√(G / ρ). With steel density ρ = 7850 kg/m³ and G = 79.3 GPa, search the 20 to 30 Hz region.",
    targetFrequency: 24.6,
    tolerance: 0.4,
    perfectBand: 0.1,
    minFrequency: 5.0,
    maxFrequency: 50.0,
    step: 0.1,
    unit: "Hz",
    breakdownThreshold: 9000,
    difficulty: "Moderate",
    structureType: "drill",
    teachingPrompts: [
      "How does a 4km steel pipe store elastic rotational energy like a giant twisting rubber band?",
      "What is 'stick-slip' vibration and why does it cause diamond drill bits to shatter underground?",
      "How do helical strakes attached to subsea risers suppress vortex-induced vibration?"
    ],
    physicsExplanation: "Subterranean rock friction locks the drill bit while the surface rotary table continues turning. Elastic torsional wind-up releases abruptly, creating a high-speed torsional wave cycle at 24.6 Hz that exceeds the shear strength of the threaded tool joints."
  },
  {
    id: 6,
    name: "Question 6: Jet Engine Turbine Blades",
    mechanicalObject: "Jet Engine Turbofan / Gas Turbine Blade Assembly",
    subtitle: "Aeromechanical Flutter & Blade Passing Frequency (BPF)",
    vibrationMode: "Coupled Bending-Torsion Blade Flutter & Campbell Diagram Crossing",
    description: "High-speed titanium-nickel turbine blades subjected to periodic aerodynamic wake impulses from upstream nozzle guide vanes.",
    realWorldPhenomenon: "Aero-engine High-Cycle Fatigue (HCF) and compressor blade flutter failure",
    formula: "BPF = (RPM / 60) * N_vanes  and  f_flutter = (1 / 2π) * √(k_blade / m_blade)",
    differentialEquation: "m · (d²h/dt²) + c · (dh/dt) + k_h · h + S_α · (d²α/dt²) = L_flutter(ω t)",
    resonanceBehavior: "Periodic wake impulses at 320 Hz cross the blade's coupled bending-torsion eigenmode on the Campbell diagram. Unsteady aerodynamic lift adds negative damping, causing high-cycle fatigue microcracks at the fir-tree blade root within millions of cycles.",
    mechanicalParams: {
      stiffness: "k_blade = 4.5 × 10⁶ N/m",
      mass: "m_blade = 0.85 kg per airfoil",
      dampingRatio: "ζ = 0.005 (aerodynamic damping near stall)",
      naturalFreqFormula: "f_n = (1 / 2π)·√(E·I / (m·L³))",
      realFailure: "Campbell diagram resonance crossing leads to micro-fretting fatigue cracks at the fir-tree blade root, liberating a blade mid-flight."
    },
    clueHint: "Coupled bending-torsion blade flutter: High-frequency Campbell intersection. Natural frequency f = (1 / 2π)·√(k / m) for stiff 0.85 kg titanium blade.",
    targetFrequency: 320.0,
    tolerance: 3.0,
    perfectBand: 0.8,
    minFrequency: 100.0,
    maxFrequency: 600.0,
    step: 1.0,
    unit: "Hz",
    breakdownThreshold: 10500,
    difficulty: "Moderate",
    structureType: "turbine",
    teachingPrompts: [
      "What is a Campbell Diagram and how do aerospace engineers use it to map resonance avoidance zones?",
      "Why is aerodynamic flutter self-excited and why does it worsen at high engine power levels?",
      "How do under-platform friction dampers convert blade vibrational energy into thermal friction dissipation?"
    ],
    physicsExplanation: "As the turbine rotor spins through stator blade wakes, each blade receives an impulse at the Blade Passing Frequency. When this matches the blade's 1st torsional eigenmode at 320 Hz, aerodynamic unsteady forces feed energy into the blade faster than internal damping can remove it."
  },
  {
    id: 7,
    name: "Question 7: London Millennium Footbridge",
    mechanicalObject: "Pedestrian Suspension Footbridge (e.g., Millennium Bridge)",
    subtitle: "Synchronous Lateral Footfall Excitation (Human Resonance)",
    vibrationMode: "1st Lateral Horizontal Flexural Mode",
    description: "A shallow suspension footbridge designed for pedestrians that swayed violently on opening day due to walking synchronization.",
    realWorldPhenomenon: "London Millennium Bridge Opening Day (June 2000) - Lateral synchronous footfall lock-in",
    formula: "f_lateral = (1 / 2L) * √(T_horizontal / m) ≈ 0.8 Hz to 1.0 Hz",
    differentialEquation: "M · (d²y/dt²) + 2·M·ζ·ω_n · (dy/dt) + M·ω_n² · y = Σ G_pedestrian · cos(ω_walk t + φ_i)",
    resonanceBehavior: "Crowds walking at ~0.85 Hz lateral pacing unconsciously synchronized their footsteps with the initial bridge movement to keep balance. This positive biomechanical feedback magnified lateral displacement from 2 mm to 70 mm.",
    mechanicalParams: {
      stiffness: "k_lateral = 1.1 × 10⁶ N/m",
      mass: "m_bridge = 1,200 kg/m",
      dampingRatio: "ζ = 0.006 (exceptionally low initial lateral damping)",
      naturalFreqFormula: "f_n = (1 / 2π)·√(k_lat / m)",
      realFailure: "2,000 pedestrians unintentionally matched their footstep cadence to the bridge sway, amplifying lateral amplitude to 70 mm."
    },
    clueHint: "Lateral footfall synchronization: Humans walk at 2 Hz vertically, which creates a lateral sway pacing at 0.85 Hz. Synchronous lock-in occurs below 1.0 Hz.",
    targetFrequency: 0.85,
    tolerance: 0.04,
    perfectBand: 0.01,
    minFrequency: 0.1,
    maxFrequency: 3.0,
    step: 0.01,
    unit: "Hz",
    breakdownThreshold: 12000,
    difficulty: "Moderate",
    structureType: "footbridge",
    teachingPrompts: [
      "Why did humans walking randomly across the bridge start walking in perfect synchronization?",
      "Why did the bridge sway sideways (horizontally) rather than up-and-down vertically?",
      "How did installing 37 fluid viscous dampers and 52 tuned mass dampers resolve the lateral oscillation?"
    ],
    physicsExplanation: "Humans walk with a vertical step frequency of 2 Hz, but their body weight shifts side-to-side at 1 Hz. When the bridge moved sideways slightly, pedestrians adjusted their stance to maintain balance, inadvertently driving the bridge in phase with its 0.85 Hz lateral eigenmode."
  },
  {
    id: 8,
    name: "Question 8: Railway Track & Railbed",
    mechanicalObject: "High-Speed Railway Steel Rail & Sleeper Bed",
    subtitle: "Pinned-Pinned Wheel Corrugation & Sleeper Resonance",
    vibrationMode: "Pinned-Pinned Beam Bending Between Sleepers",
    description: "Continuously welded high-carbon steel rails vibrating under periodic train wheel axle loadings.",
    realWorldPhenomenon: "Railway rail corrugation roar, track sleeper ballast pulverization & wheel flat impacts",
    formula: "f_pinned = (n² * π / 2 * L_sleeper²) * √(E*I / m_rail)",
    differentialEquation: "EI · (∂⁴w/∂x⁴) + m_rail · (∂²w/∂t²) + c_pad · (∂w/∂t) + k_pad · w = P_wheel · δ(x - v t)",
    resonanceBehavior: "At 88.5 Hz, the steel rail experiences pinned-pinned flexural resonance between consecutive sleeper ties. Dynamic wheel-rail contact force spikes from 100 kN to 350 kN, wearing short-pitch corrugation washboards that crack railway fasteners.",
    mechanicalParams: {
      stiffness: "EI_rail = 6.4 × 10⁶ N·m² (UIC60 Rail Profile)",
      mass: "m_rail = 60 kg/m (sleeper spacing L = 0.6 m)",
      dampingRatio: "ζ = 0.025 (pad elastomeric stiffness)",
      naturalFreqFormula: "f_n = (π / 2L²)·√(EI / m)",
      realFailure: "Short-pitch rail corrugations grow exponentially, causing extreme high-frequency acoustic noise and fastening clip fatigue fracture."
    },
    clueHint: "Pinned-pinned rail beam mode: Supported on sleeper ties spaced L = 0.6 m. Formula f = (π / 2L²)·√(EI / m). Calculate using EI = 6.4×10⁶ N·m² and m = 60 kg/m.",
    targetFrequency: 88.5,
    tolerance: 1.0,
    perfectBand: 0.25,
    minFrequency: 20.0,
    maxFrequency: 160.0,
    step: 0.5,
    unit: "Hz",
    breakdownThreshold: 13500,
    difficulty: "Difficult",
    structureType: "railway",
    teachingPrompts: [
      "What is the 'pinned-pinned' mode of a railway track supported periodically by sleepers?",
      "How does a flat spot on a freight train wheel act as an impact harmonic exciter?",
      "Why do modern high-speed rails require tuned rail dampers clipped directly to the rail web?"
    ],
    physicsExplanation: "The rail acts as a continuous beam periodically clamped by elastic rail pads onto concrete ties. Passing wheelsets at high speeds excite the 88.5 Hz pinned-pinned vibration mode, leading to microscopic wear valleys (corrugation) that amplify dynamic wheel/rail contact forces."
  },
  {
    id: 9,
    name: "Question 9: Automobile Suspension Chassis",
    mechanicalObject: "Automotive Suspension & Chassis (Quarter-Car Model)",
    subtitle: "Sprung vs Unsprung Mass Resonance (Wheel Hop & Body Bounce)",
    vibrationMode: "Two-Degree-of-Freedom (2-DOF) Coupled Wheel Hop & Bounce Mode",
    description: "A vehicle quarter-car suspension crossing periodic road washboard corrugations matching suspension natural frequencies.",
    realWorldPhenomenon: "Washboard road vibration, shock absorber cavitation, and wheel hop loss of traction",
    formula: "ω_bounce = √(k_susp / m_body)  and  ω_hop = √((k_susp + k_tire) / m_wheel)",
    differentialEquation: "[M] · {d²X/dt²} + [C] · {dX/dt} + [K] · {X} = {F_road(ω t)} (2-DOF Coupled Bounce & Hop)",
    resonanceBehavior: "At 12.4 Hz, the unsprung tire and axle mass resonates in 'wheel hop' mode against road corrugation. The tire loses contact with the tarmac completely, inducing cyclic impact spikes that fatigue suspension control arm ball joints.",
    mechanicalParams: {
      stiffness: "k_susp = 32,000 N/m, k_tire = 220,000 N/m",
      mass: "m_sprung = 400 kg (body), m_unsprung = 45 kg (wheel/axle)",
      dampingRatio: "ζ = 0.3 (normal shock absorber) → ζ = 0.04 (blown shock absorber)",
      naturalFreqFormula: "f_hop = (1 / 2π)·√((k_s + k_t) / m_u)",
      realFailure: "Blown shock absorber dampers cause the tire to bounce completely off the tarmac, causing total loss of braking and suspension arm fatigue."
    },
    clueHint: "2-DOF wheel hop mode: Unsprung wheel/axle mass m_u = 45 kg resonating between tire stiffness (220,000 N/m) and suspension spring (32,000 N/m).",
    targetFrequency: 12.4,
    tolerance: 0.25,
    perfectBand: 0.06,
    minFrequency: 2.0,
    maxFrequency: 25.0,
    step: 0.1,
    unit: "Hz",
    breakdownThreshold: 15000,
    difficulty: "Difficult",
    structureType: "vehicle",
    teachingPrompts: [
      "What is the difference between body bounce frequency (1-2 Hz) and wheel hop frequency (10-15 Hz)?",
      "Why do dirt roads develop rhythmic 'washboard' ripples at precise spacing?",
      "How do hydraulic shock absorbers dissipate vibrational kinetic energy into viscous heat?"
    ],
    physicsExplanation: "The automotive suspension is a classical 2-DOF vibrating system. The heavier car body has a low natural bounce frequency (~1.2 Hz), while the light wheel/tire assembly resonates at 12.4 Hz. Without active shock damping, driving over corrugated terrain causes violent wheel hop, breaking ball joints and control arms."
  },
  {
    id: 10,
    name: "Question 10: Industrial Piping System",
    mechanicalObject: "Industrial Power Plant Piping & Shell Cavity",
    subtitle: "Acoustic-Structural Pipe Vibration & Water Hammer Resonance",
    vibrationMode: "Acoustic Standing Wave Coupling with Thin-Walled Pipe Flexure",
    description: "High-pressure fluid piping system in a power generation facility subjected to cyclic valve pulsations and acoustic cavity standing waves.",
    realWorldPhenomenon: "Power plant feed-water pipe bursts, acoustic fatigue, and reciprocating compressor piping resonance",
    formula: "f_pipe = (c_fluid / 4L)  and  f_beam = (3.56 / 2π * L²) * √(E*I / m_fluid_pipe)",
    differentialEquation: "∂²p/∂t² - c² · ∂²p/∂x² = -(ρ_0 / A) · (∂Q/∂t)  coupled to  m_pipe · (d²y/dt²) + k · y = p(x,t) · A_eff",
    resonanceBehavior: "Fluid acoustic wave pulses matching the mechanical pipe flexural frequency at 56.4 Hz set up strong acoustic-structural standing wave coupling. Cyclic hoop pressure pulses exceed the 15 MPa fatigue threshold, bursting high-pressure elbow welds.",
    mechanicalParams: {
      stiffness: "EI_pipe = 8.5 × 10⁷ N·m² (Schedule 80 Alloy Steel Pipe)",
      mass: "m_total = 210 kg/m (including high-density pressurized fluid)",
      dampingRatio: "ζ = 0.009 (rigid pipe hanger mounts with poor elastomeric isolation)",
      naturalFreqFormula: "f_acoustic = (c_fluid / 2L) * n",
      realFailure: "Coincidence of fluid acoustic wave frequency with mechanical structural beam mode causes pipe rupture and catastrophic steam blow-out."
    },
    clueHint: "Acoustic-structural wave coincidence: Fluid pressure standing waves locked with beam flexure of 14m pipe span. High-frequency eigenmode between 50 and 65 Hz.",
    targetFrequency: 56.4,
    tolerance: 0.7,
    perfectBand: 0.15,
    minFrequency: 10.0,
    maxFrequency: 110.0,
    step: 0.2,
    unit: "Hz",
    breakdownThreshold: 18000,
    difficulty: "Difficult",
    structureType: "pipe",
    teachingPrompts: [
      "How does periodic fluid flow or reciprocating pump strokes excite mechanical pipe vibration?",
      "What is acoustic-structural coupling and why is it dangerous when fluid sound speed matches structural wave speed?",
      "How do pulsation dampener bottles and flexible bellows suppress pressure waves in pipe systems?"
    ],
    physicsExplanation: "Pressure pulsations from upstream compressors propagate through the liquid/steam column as acoustic standing waves. When the acoustic pulsation frequency coincides with the pipe span's mechanical natural flexural frequency (56.4 Hz), intense cyclic stresses induce rapid fatigue cracking at elbow welds and flange gaskets."
  }
];
